version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "Dockerfile" }}
          paths: ~/caches/images.tar
      - run:
          name: Check cache file, if not exists then pull images and generate cache.
          command: |
            if [ ! -f ~/caches/images.tar ]; then
              docker build -t neko .
              mkdir -p ~/caches
              docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ~/caches/images.tar
            fi
      - save_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "api/Dockerfile" }}
          paths: ~/caches/images.tar
      - run:
          name: finish cacheing
          command: echo "finish cache"

  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "api/Dockerfile" }}
          paths: ~/caches/images.tar
      - run: 
          name: docker load
          command: if test -d ~/caches; then docker load -i ~/caches/images.tar; fi
      - run:
          name: Build Docker Image
          command: docker build -t neko .
      - run:
            name: docker up
            command: |
                 docker run -itd --name=neko neko
      - run:
            name: finish build
            command: echo "finish build"

  push-image:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: build image 
          command: |
            echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json

            docker build -f Dockerfile --rm=false -t asia.gcr.io/voltaic-quest-176113/neko:latest .
      - run: 
          name: push image
          command: |
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project voltaic-quest-176113
            gcloud docker -- push asia.gcr.io/voltaic-quest-176113/neko:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - generate_cache:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only: master
          requires:
            - generate_cache
      - push-image:
          filters:
            branches:
              only: master
          requires:
            - build
